# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{react}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kriss 'nu7hatch' Kowalik"]
  s.date = %q{2010-08-17}
  s.default_executable = %q{react}
  s.description = %q{A simple application that allows for remote execution of commands.}
  s.email = %q{kriss.kowalik@gmail.com}
  s.executables = ["react"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "bin/react",
     "examples/commands.yml",
     "lib/react.rb",
     "react.gemspec",
     "test/react_test.rb",
     "test/teststrap.rb"
  ]
  s.homepage = %q{http://github.com/nu7hatch/react}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Redis based remote command executor.}
  s.test_files = [
    "test/teststrap.rb",
     "test/react_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<riot>, [">= 0.11.3"])
      s.add_runtime_dependency(%q<daemons>, [">= 0"])
    else
      s.add_dependency(%q<riot>, [">= 0.11.3"])
      s.add_dependency(%q<daemons>, [">= 0"])
    end
  else
    s.add_dependency(%q<riot>, [">= 0.11.3"])
    s.add_dependency(%q<daemons>, [">= 0"])
  end
end

